### ISSUE TITLE
driver should refrain from using literals where possible, here  you could use something like MAX_CS

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#10]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L2077

**Comment by miquelraynal** [comment]
I forgot to replace this one but there is a structure with the controller capabilities depending on the compatible string. This structure embeds the maximum number of CS (depends on the NFC version).
