### ISSUE TITLE
shouldnt error cases after the kmalloc free the allocated memory?

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#12]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L937

**Comment by miquelraynal** [comment]
You are right, I forgot almost all kfree when I added the kmalloc's.
Fixed all the functions that used heap allocation.
