### ISSUE TITLE
you could have saved a ndcr reg read if you check ENABLE in the calling routine, that way the marvell_nfc_hw_ecc_enable/disable would be called only if NDCR was set/cleared

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#15]
https://github.com/miquelraynal/linux/blob/ed97672cb248ece96dd621336ead3030390f2eb8/drivers/mtd/nand/marvell_nand.c#L1269

**Comment by miquelraynal** [comment]
Closing this issue as it is related to another one also closed.
