### ISSUE TITLE
this could allocate 4K on stack, seems too big to me

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#17]
https://github.com/miquelraynal/linux/blob/ed97672cb248ece96dd621336ead3030390f2eb8/drivers/mtd/nand/marvell_nand.c#L1436

**Comment by miquelraynal** [comment]
For sure, this is a mistake.
I haven't pushed/sent a new version yet but I removed all dynamically allocated buffers after Boris' review.
