### ISSUE TITLE
shouldnt the return code of this routine be checked?

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#3]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L518

**Comment by miquelraynal** [comment]
The calling functions are void anyway, the overall operation will fail and the operation that follow are pointless in that case.

I prefer not to add too much error logic when there is no actual need because it makes the code less readable. Are you OK with that ?

**Comment by oferhz** [comment]
question is: does it make any sense to run the rest of the routines if ND_RUN failed to be ready, I think the routine should return on error, no?

**Comment by miquelraynal** [comment]
Right, I changed all the calls to ->prepare_cmd().
