### ISSUE TITLE
enables and disables the interrupt NDCR_RDYM bit, is this mandatory? 	these read/writes will slow the overall performance, no?

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#4]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L480

**Comment by miquelraynal** [comment]
The overhead of reading/writing these registers while waiting for the NAND chip to be ready is pointless compared to the read/write delays. And the operation is done only once per page.
