### ISSUE TITLE
shouldnt this routine also handle none NAND_CLE | NAND_ALE cases? if not then could return on routine entry

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#5]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L504

**Comment by miquelraynal** [comment]
I think the organization of this function is what must be done and what want NAND maintainers, it is widely inspired from (almost) up-to-date NAND controller drivers and I do not think there is something to change in it.

Plus, I don't really see the need to return on routine entry with this pattern. It would not even delete an indentation level.

**Comment by oferhz** [comment]
ok
