### ISSUE TITLE
this could have a more meaningful name

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#7]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L1848

**Comment by miquelraynal** [comment]
What do you suggest ?

This is really a temporary variable used multiple times for multiple purposes. I took it from sunxi_nand driver as a reference. But you are right it is not that clear. I split its use into two local variables "u32 cs" and "u32 rb".

I know it is not very explicit
