### ISSUE TITLE
shouldnt the switch have a default case?

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#8]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L1924

**Comment by miquelraynal** [comment]
Well, technically there is no way tmp could be outside of [0;3] because it is an u32 and it is checked that it is less than 4. But I added a default case with a return -EINVAL for clarity.
