### ISSUE TITLE
this is set above but never gets changed to another value, is this check really needed?

### ISSUE THREAD

**Issue by oferhz** [miquelraynal/linux#9]
https://github.com/miquelraynal/linux/blob/f37ca4775976f77465a9cfb27b59f4b1bf2c505c/drivers/mtd/nand/marvell_nand.c#L2032

**Comment by miquelraynal** [comment]
No, this may actually be changed, see comment behind:

	/*
	 * Default to HW ECC engine mode. If the nand-ecc-mode property is given
	 * in the DT node, this entry will be overwritten in nand_scan_ident().
	 */
nand->ecc.mode = NAND_ECC_HW;

[...]

nand_scan_ident(...);
